repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: bash -c "source .venv/bin/activate && pytest nitoronlinetestportal/ && deactivate"
        language: python
        pass_filenames: false
        always_run: true
